export const DSIII_QUEST_TAGS = {
  leonhard: {value: 'Leonhard', colour: '#84A6D6'},
  greirat: {value: 'Greirat', colour: '#4382BB'},
  hawkwood: {value: 'Hawkwood', colour: '#BEB4C5'},
  yoel: {value: 'Yoel', colour: '#E6A57E'},
  cornyx: {value: 'Cornyx', colour: '#218B82'},
  irina: {value: 'Irina', colour: '#EB96AA'},
  siegward: {value: 'Siegward', colour: '#C54B6C'},
  anri: {value: 'Anri', colour: '#C47482'},
  sirris: {value: 'Sirris', colour: '#C6C9D0'},
  orbeck: {value: 'Orbeck', colour: '#F9968B'},
  karla: {value: 'Karla', colour: '#F27348'},
  lapp: {value: 'Lapp', colour: '#76CDCD'},
  anriBadEnd: {value: 'Anri - Bad End', colour: '#C47482'},
  anriGoodEnd: {value: 'Anri - Good End', colour: '#C47482'},
  irinaGoodEnd: {value: 'Irina - Good End', colour: '#EB96AA'},
  ashesOfAriandel: {value: 'Ashes of Ariandel', colour: '#7B92AA'},
  theRingedCity: {value: 'The Ringed City', colour: '#A15D98'},
};
